language: r
warnings_are_errors: false
sudo: false
cache: packages

# blacklist
# branches:
#   except:
#     - master

# whitelist
branches:
  only:
    - master
    # Change to release once released

# Code coverage
r_packages:
  - devtools


after_success:
- Rscript -e 'install.packages("covr"); library("covr"); codecov()'
