language: r
cache: packages
sudo: required
warnings_are_errors: false

# blacklist
# branches:
#   except:
#     - master

# whitelist
branches:
  only:
    - master
    - readCharacters
    # Change to release once released

r_binary_packages:
  - ape
  - covr
  - devtools
  - knitr
  - phangorn
  - roxygen2
  - shiny
  - testthat

r_packages:
  - TreeSearch

before_script:
- Rscript -e 'install.packages("TreeSearch")'
- Rscript -e 'devtools::install_github("ms609/TreeSearch")'

# Code coverage
after_success:
- Rscript -e 'library("covr"); codecov()'
