language: r

cache: packages
warnings_are_errors: false

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - libv8-dev

# whitelist
branches:
  only:
    - master
    - release

r_github_packages:
  - ms609/TreeSearch

# Code coverage
r_packages:
  - covr
after_success:
- Rscript -e 'library("covr"); codecov(line_exclusions = list("R/svg.R" = c(1:514)))'
