language: r
cache: packages
sudo: required
warnings_are_errors: false

# blacklist
# branches:
#   except:
#     - master

# whitelist
branches:
  only:
    - master
    - Character-names
    # Change to release once released

# Code coverage
r_binary_packages:
  - ape
  - covr
  - devtools
  - knitr
  - phangorn
  - roxygen2
  - shiny
  - testthat

r_github_packages:
  - ms609/TreeSearch

after_success:
- Rscript -e 'library("covr"); codecov()'
