language: r
cache: packages
warnings_are_errors: false

# blacklist
# branches:
#   except:
#     - master

# whitelist
branches:
  only:
    - master
    - Character-names
    # Change to release once released

# Code coverage
r_binary_packages:
  - covr
  - devtools

after_success:
- Rscript -e 'library("covr"); codecov()'
