language: r
cache: packages
sudo: required
warnings_are_errors: false

r:
- release

# blacklist
# branches:
#   except:
#     - master

# whitelist
branches:
  only:
    - master
    - release

r_binary_packages:
  - ape
  - covr
  - devtools
  - knitr
  - phangorn
  - roxygen2
  - shiny
  - testthat
  - {T}ree{S}earch

#github_packages:
#  - ms609/TreeSearch

# Code coverage
after_success:
- Rscript -e 'library("covr"); codecov(line_exclusions = list("R/svg.R" = c(1:514)))'
