---
title: "Inapplicable data"
author: "Martin D Brazeau (m.brazeau@imperial.ac.uk), Thomas Guillerme (guillert@tcd.ie) and Martin R Smith (martin.smith@durham.ac.uk)""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa-old-doi-prefix.csl
vignette: >
  %\VignetteIndexEntry{Index}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Inapplicable data in a parsimony setting

This series of vignettes works through the inapplicable algorithm proposed by Brazeau _et al._ [-@ThisStudy].

## Contents

- The Fitch Algorithm:
  - [An introduction](Fitch.html)
    - Status: In progress (TG)
  - [Shortcomings](Problems.html)
    - Status: In progress (MS)
  - [Proposed solutions](FailedSolutions.html)
    - Status: Not allocated
  
- Our algorithm:
  - [An introduction](OurSolution.html)
    - Status: Not allocated
  - [A description](OurAlgorithm.html)
    - Status: Draft complete? (TG)
  - [Implications for character coding](CodingData.html)
    - Status: In progress (MS)
  - [Coding neomorphic characters](Neomorphics.html)
    - Status: In progress (MS)
  - [Coding ambiguity](AmbiguousData.html)
    - Status: Draft complete (MS)
  - [Some worked examples](Examples.html)
    - Status: Complete? (MS)

## References
